[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"