[build]
builder = "herokuish"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
DISABLE_DATABASE_ENVIRONMENT_CHECK = "1"