# Recurring jobs configuration
development:
  # Data sync jobs
  full_data_sync:
    class: DataSyncJob
    args: ['full']
    schedule: every 6 hours
  
  daily_appointment_reminders:
    class: AppointmentReminderJob
    args: ['daily']
    schedule: at 9am every day
  
  hourly_appointment_reminders:
    class: AppointmentReminderJob
    args: ['hourly']
    schedule: every hour

production:
  # Data sync jobs
  full_data_sync:
    class: DataSyncJob
    args: ['full']
    schedule: every 4 hours
  
  daily_appointment_reminders:
    class: AppointmentReminderJob
    args: ['daily']
    schedule: at 9am every day
  
  hourly_appointment_reminders:
    class: AppointmentReminderJob
    args: ['hourly']
    schedule: every hour
  
  # System maintenance
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
